CREATE TABLE AccidentDetails (
    ACCIDENT_NO CHAR(20) NOT NULL,
    ACCIDENT_DATE DATE NOT NULL,
    ACCIDENT_TIME TIME(0) NOT NULL,

    ACCIDENT_TYPE_DESC VARCHAR(200) NOT NULL,

    DCA_CODE SMALLINT NOT NULL,
    DCA_DESC VARCHAR(200)NOT NULL,
    
    LIGHT_CONDITION TINYINT NULL,
    LIGHT_CONDITION_DESC VARCHAR(200) NULL,
    
    POLICE_ATTEND TINYINT NULL,
    POLICE_ATTEND_DESC VARCHAR(50) NULL,
    
    ROAD_GEOMETRY TINYINT NULL,
    ROAD_GEOMETRY_DESC VARCHAR(200) NULL,
    
    SEVERITY TINYINT NOT NULL,
    SEVERITY_DESC VARCHAR(50) NOT NULL,
    
    SPEED_ZONE SMALLINT NULL,
    SPEED_ZONE_DESC VARCHAR(50) NULL,
    
    RMA VARCHAR(20) NOT NULL,
 
    CONSTRAINT PK_AccidentDetails PRIMARY KEY (ACCIDENT_NO),
    CONSTRAINT CK_Accident_Severity CHECK (SEVERITY BETWEEN 1 AND 4),
    CONSTRAINT CK_Accident_SpeedZone CHECK (SPEED_ZONE IS NULL OR SPEED_ZONE BETWEEN 0 AND 150 OR SPEED_ZONE IN (777, 888, 999))
)
GO

CREATE INDEX IX_Accident_Date ON AccidentDetails (ACCIDENT_DATE)
CREATE INDEX IX_Accident_Severity ON AccidentDetails (SEVERITY);