CREATE TABLE Vehicle_Characteristics (
    ACCIDENT_NO CHAR(20) NOT NULL,
    VEHICLE_ID CHAR(1) NOT NULL,
    VEHICLE_YEAR_MANUF SMALLINT NULL,
    VEHICLE_TYPE TINYINT NOT NULL,
    VEHICLE_TYPE_DESC VARCHAR(50) NOT NULL,
    VEHICLE_BODY_STYLE VARCHAR(10) NOT NULL,
    VEHICLE_MAKE VARCHAR(10) NOT NULL,
    VEHICLE_MODEL VARCHAR(30) NOT NULL,
    CONSTRUCTION_TYPE CHAR(1) NOT NULL,
    FUEL_TYPE CHAR(1) NOT NULL,
    FUEL_TYPE_DESC VARCHAR(20) NOT NULL,
    REG_STATE CHAR(1) NOT NULL,
    VEHICLE_COLOUR_1 VARCHAR(3) NOT NULL,
    TRAILER_TYPE CHAR(1) NOT NULL,
    TRAILER_TYPE_DESC VARCHAR(30) NOT NULL,
    NO_OF_WHEELS TINYINT NULL,
    NO_OF_CYLINDERS TINYINT NULL,
    SEATING_CAPACITY TINYINT NULL,
    TARE_WEIGHT INT NULL,
    VEHICLE_WEIGHT INT NULL,
    CARRY_CAPACITY INT NULL,
    CUBIC_CAPACITY INT NULL,

    CONSTRAINT PK_VehChar PRIMARY KEY (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT FK_VehChar_Accident FOREIGN KEY (ACCIDENT_NO) REFERENCES AccidentDetails (ACCIDENT_NO),
    CONSTRAINT CK_VehChar_Year CHECK (VEHICLE_YEAR_MANUF IS NULL OR VEHICLE_YEAR_MANUF BETWEEN 1901 AND 2026),
    CONSTRAINT CK_VehChar_Tare CHECK (TARE_WEIGHT IS NULL OR TARE_WEIGHT > 0),
    CONSTRAINT CK_VehChar_Weight CHECK (VEHICLE_WEIGHT IS NULL OR VEHICLE_WEIGHT > 0),
    CONSTRAINT CK_VehChar_Wheels CHECK (NO_OF_WHEELS IS NULL OR NO_OF_WHEELS >= 0),
    CONSTRAINT CK_VehChar_Cyl CHECK (NO_OF_CYLINDERS IS NULL OR NO_OF_CYLINDERS >= 0),
    CONSTRAINT CK_VehChar_Seats CHECK (SEATING_CAPACITY IS NULL OR SEATING_CAPACITY >= 0)
);
GO

CREATE INDEX IX_VehChar_AccidentNo ON Vehicle_Characteristics (ACCIDENT_NO);
CREATE INDEX IX_VehChar_Type ON Vehicle_Characteristics (VEHICLE_TYPE);
GO