CREATE TABLE Vehicle_Characteristics  (
    ACCIDENT_NO CHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    VEHICLE_YEAR_MANUF SMALLINT NULL,
    VEHICLE_BODY_STYLE VARCHAR(50) NULL,
    VEHICLE_MAKE VARCHAR(50) NULL,
    VEHICLE_MODEL VARCHAR(50) NULL,
    VEHICLE_TYPE TINYINT NOT NULL,
    VEHICLE_TYPE_DESC VARCHAR(200) NOT NULL,
    FUEL_TYPE VARCHAR(30) NULL,
    NO_OF_WHEELS TINYINT NULL,
    NO_OF_CYLINDERS TINYINT NULL,
    SEATING_CAPACITY TINYINT NULL,
    VEHICLE_COLOUR_1 VARCHAR(30) NULL,
    TARE_WEIGHT INT NULL,
    
    CONSTRAINT PK_Vehicle_Charcteristics PRIMARY KEY (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT FK_VehChar_Accident FOREIGN KEY (ACCIDENT_NO) REFERENCES AccidentDetails (ACCIDENT_NO),
    CONSTRAINT CK_Manufactured_Year CHECK (VEHICLE_YEAR_MANUF BETWEEN 1900 AND 2026),
    CONSTRAINT CK_Wheel_count CHECK (NO_OF_WHEELS >= 0),
    CONSTRAINT CK_cylinder_COUNT CHECK (NO_OF_CYLINDERS >= 0),
    CONSTRAINT CK_seating_capacity CHECK (SEATING_CAPACITY >= 0)
)
GO

CREATE INDEX IX_VehCar_AccidentNumber ON  Vehicle_Characteristics(ACCIDENT_NO)
CREATE INDEX IX_VehCar_VehicleID ON  Vehicle_Characteristics(VEHICLE_ID)
CREATE INDEX IX_VehCar_VehicleModel ON Vehicle_Characteristics(VEHICLE_MODEL);
GO