CREATE TABLE Vehicle_Crash_Involvement  (
    ACCIDENT_NO CHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    VEHICLE_DCA_CODE VARCHAR(20) NULL,
    INITIAL_DIRECTION VARCHAR(20) NULL,
    FINAL_DIRECTION  VARCHAR(20) NULL,
    INITIAL_IMPACT VARCHAR(50) NULL,
    DRIVER_INTENT VARCHAR(60) NULL,
    VEHICLE_MOVEMENT VARCHAR(50) NULL,
    ROAD_SURFACE_TYPE TINYINT NULL,
    ROAD_SURFACE_TYPE_DESC VARCHAR(100) NULL,
    TRAFFIC_CONTROL_DESC VARCHAR (100) NULL,
    LEVEL_OF_DAMAGE TINYINT NULL,
    CAUGHT_FIRE  TINYINT NULL,
    LAMPS TINYINT NULL,
    TOWED_AWAY_FLAG TINYINT NULL,
    TOTAL_NO_OCCUPANTS SMALLINT NULL,
    VEHICLE_MAKE VArCHAR(50) NULL,
    VEHICLE_MODEL VARCHAR(50) NULL,
    
    CONSTRAINT PK_Vehicle_Crash_Involvement PRIMARY KEY (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT FK_VehCrash_VehChar FOREIGN KEY (ACCIDENT_NO, VEHICLE_ID) REFERENCES Vehicle_Characteristics (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT CK_Damage_level CHECK (LEVEL_OF_DAMAGE BETWEEN 0 AND 9),
    CONSTRAINT CK_caught_Fire CHECK (CAUGHT_FIRE IN (0, 1, 2, 9)),
    CONSTRAINT CK_Lamps CHECK (LAMPS IN (0, 1, 2, 9)),
    CONSTRAINT CK_TOWED_AWAY_FLAG CHECK (TOWED_AWAY_FLAG IN (0, 1, 2, 9))
)
GO

CREATE INDEX IX_CrashInv_VehicleMAKE ON  Vehicle_Crash_Involvement (VEHICLE_MAKE)
CREATE INDEX IX_CrashInv_VehicleMODEL ON Vehicle_Crash_Involvement(VEHICLE_MODEL);
GO