CREATE TABLE Vehicle_Crash_Involvement (
    ACCIDENT_NO CHAR(20) NOT NULL,
    VEHICLE_ID CHAR(1) NOT NULL,

    VEHICLE_DCA_CODE SMALLINT  NOT NULL,
    INITIAL_DIRECTION VARCHAR(2) NOT NULL,
    FINAL_DIRECTION VARCHAR(2) NOT NULL,
    DRIVER_INTENT SMALLINT NOT NULL,
    DRIVER_INTENT_DESC VARCHAR(25) NOT NULL,
    VEHICLE_MOVEMENT SMALLINT NOT NULL,
    ROAD_SURFACE_TYPE SMALLINT NOT NULL,
    ROAD_SURFACE_TYPE_DESC VARCHAR(12) NOT NULL,
    TRAFFIC_CONTROL SMALLINT NOT NULL,
    TRAFFIC_CONTROL_DESC VARCHAR(20) NOT NULL,
    INITIAL_IMPACT CHAR(1) NOT NULL,
    INITIAL_IMPACT_DESC VARCHAR(20) NOT NULL,
    LEVEL_OF_DAMAGE SMALLINT NOT NULL,
    LEVEL_OF_DAMAGE_DESC VARCHAR(30) NOT NULL,
    CAUGHT_FIRE SMALLINT NOT NULL,
    CAUGHT_FIRE_DESC VARCHAR(15) NOT NULL,
    LAMPS SMALLINT NOT NULL,
    TOWED_AWAY_FLAG SMALLINT NOT NULL,
    TOTAL_NO_OCCUPANTS TINYINT NULL,

    CONSTRAINT PK_VehCrash PRIMARY KEY (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT FK_VehCrash_VehChar FOREIGN KEY (ACCIDENT_NO, VEHICLE_ID) REFERENCES Vehicle_Characteristics (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT CK_VehCrash_DCA CHECK (VEHICLE_DCA_CODE IN (-1, 1, 2, 3, 8)),
    CONSTRAINT CK_VehCrash_Surface CHECK (ROAD_SURFACE_TYPE IN (-1, 1, 2, 3, 9)),
    CONSTRAINT CK_VehCrash_Damage CHECK (LEVEL_OF_DAMAGE IN (-1, 1, 2, 3, 4, 5, 6, 9)),
    CONSTRAINT CK_VehCrash_Fire CHECK (CAUGHT_FIRE IN (-1, 0, 1, 2, 9)),
    CONSTRAINT CK_VehCrash_Lamps CHECK (LAMPS IN (-1, 0, 1, 2, 9)),
    CONSTRAINT CK_VehCrash_Towed CHECK (TOWED_AWAY_FLAG IN (-1, 1, 2, 9)),
    CONSTRAINT CK_VehCrash_Intent CHECK (DRIVER_INTENT = -1 OR DRIVER_INTENT BETWEEN 1 AND 19 OR DRIVER_INTENT = 99),
    CONSTRAINT CK_VehCrash_Move CHECK (VEHICLE_MOVEMENT = -1 OR VEHICLE_MOVEMENT BETWEEN 1 AND 19 OR VEHICLE_MOVEMENT = 99),
    CONSTRAINT CK_VehCrash_Traffic CHECK (TRAFFIC_CONTROL = -1 OR TRAFFIC_CONTROL BETWEEN 0 AND 15 OR TRAFFIC_CONTROL = 99),
    CONSTRAINT CK_VehCrash_Occ CHECK (TOTAL_NO_OCCUPANTS IS NULL OR TOTAL_NO_OCCUPANTS >= 0)
);
GO

CREATE INDEX IX_VehCrash_Damage ON Vehicle_Crash_Involvement (LEVEL_OF_DAMAGE);
CREATE INDEX IX_VehCrash_Impact ON Vehicle_Crash_Involvement (INITIAL_IMPACT);
GO