CREATE TABLE SevereCrashesBySpeedZone (
    ACCIDENT_YEAR SMALLINT NOT NULL,
    SPEED_ZONE_DESC VARCHAR(50) NOT NULL,

    FATAL_CRASHES INT NOT NULL DEFAULT 0,
    SERIOUS_INJURY_CRASHES INT NOT NULL DEFAULT 0,
    TOTAL_SEVERE_CRASHES INT NOT NULL DEFAULT 0,
    
    CONSTRAINT PK_SevereCrashesBySpeedZone PRIMARY KEY (ACCIDENT_YEAR, SPEED_ZONE_DESC)
);
GO