CREATE TABLE AccidentOutcomeSummary (
    ACCIDENT_NO CHAR(20) NOT NULL,
    NO_OF_VEHICLES TINYINT NOT NULL, 
    NO_PERSONS_KILLED TINYINT NOT NULL, 
    NO_PERSONS_SERIOUS_INJ TINYINT NOT NULL, 
    NO_PERSONS_OTHER_INJ TINYINT NOT NULL, 
    NO_PERSONS_NOT_INJ TINYINT NOT NULL,
 
    CONSTRAINT PK_AccidentOutcome PRIMARY KEY (ACCIDENT_NO),
    CONSTRAINT FK_Outcome_Accident FOREIGN KEY (ACCIDENT_NO) REFERENCES AccidentDetails (ACCIDENT_NO),
    CONSTRAINT CK_Outcome_Vehicles CHECK (NO_OF_VEHICLES > 0),
    CONSTRAINT CK_Outcome_Killed CHECK (NO_PERSONS_KILLED >= 0)
);