CREATE TABLE Vehicle_Crash_Involvement  (
    ACCIDENT_NO VARCHAR(20) NOT NULL,
    VEHICLE_ID VARCHAR(20) NOT NULL,
    INITIAL_DIRECTION  VARCHAR(20) CHAR NOT NULL,
    FINAL_DIRECTION  VARCHAR(20) CHAR NOT NULL,
    -- VEHICLE_MAKE  VARCHAR(50) NOT NULL,
    -- VEHICLE_MODEL VARCHAR(50) NOT NULL,
    -- VEHICLE_TYPE_DESC VARCHAR(200) NOT NULL,
    TRAFFIC_CONTROL_DESC VARCHAR (100)CHAR NOT NULL,
    LEVEL_OF_DAMAGE TINYINT NOT NULL,
    CAUGHT_FIRE  CHAR(1) NOT NULL
    INITIAL_IMPACT VARCHAR(50) NOT NULL
    TOWED_AWAY_FLAG CHAR(1) NOT NULL
    
    CONSTRAINT PK_Vehicle_Charcteristics PRIMARY KEY (ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT FK_CrashInv_VehicleCharcteristics FOREIGN KEY (ACCIDENT_NO, VEHICLE_ID) REFERENCES Vehicle_Characteristics(ACCIDENT_NO, VEHICLE_ID),
    CONSTRAINT CK_Damage_level CHECK (LEVEL_OF_DAMAGE BETWEEN 0 AND 9),
    CONSTRAINT CK_caught_Fire CHECK (CAUGHT_FIRE IN ('Y', 'N', '1', '2')),
    CONSTRAINT CK_TOWED_AWAY_FLAG CHECK (TOWED_AWAY_FLAGIN ('Y', 'N', '1', '2')),
)
GO

CREATE INDEX IX_CrashInv_VehicleMAKE ON  Vehicle_Crash_Involvement (VEHICLE_MAKE)
CREATE INDEX IX_CrashInv_VehicleMODEL ON Vehicle_Crash_Involvement(VEHICLE_MODEL);