CREATE TABLE SevereCrashesBySpeedZone (
    SEVERE_ZONE_ID INT IDENTITY(1,1) NOT NULL,
    SPEED_ZONE TINYINT NULL,
    SPEED_ZONE_CATEGORY VARCHAR(50) NOT NULL,
    ACCIDENT_YEAR SMALLINT NOT NULL,
    SEVERE_CRASH_COUNT INT NOT NULL,

    CONSTRAINT PK_SevereByZone PRIMARY KEY (SEVERE_ZONE_ID),
    CONSTRAINT UQ_SevereByZone UNIQUE (SPEED_ZONE_CATEGORY, ACCIDENT_YEAR, SPEED_ZONE),
    CONSTRAINT CK_SevereByZone_Year CHECK (ACCIDENT_YEAR BETWEEN 2012 AND 2026),
    CONSTRAINT CK_SevereByZone_Count CHECK (SEVERE_CRASH_COUNT > 0)
);
GO